title: "[Announcement] "
labels: []
body:
  - type: markdown
    attributes:
      value: Use this template for releases, new plugins, or community news.
  - type: textarea
    id: announcement
    attributes:
      label: Announcement
    validations:
      required: true
